services:
  da-dev-cleaner:
    image: ubuntu:22.04
    entrypoint: [ "bash", "-c", "rm -r /usr/share/docassemble/backup/files/000/" ]
    volumes:
      - ./docassemble:/usr/share/docassemble/backup
  docassemble:
    hostname: docassemble.docker
    image: ghcr.io/dblevin1/docassemble:1.6.3.1
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/docassemble:/usr/share/docassemble/backup
      - /mnt:/mnt/ro:ro
      - ./volumes/pip_conf:/var/www/.pip
      - /mnt/fakeMnt:/mnt/fakeMnt
      - ./volumes/live-config/config.yml:/usr/share/docassemble/config/config.yml
    stop_grace_period: 1m
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - 80:80
      # - 6379:6379 # Redis
      # - 5432:5432 # Postgres
      - 5672:5672 # RabbitMQ
    environment:
      - CONTAINERROLE=web:celery:cron:rabbitmq:log:mail # :sql:redis
      - TIMEZONE=America/Phoenix
      - DBHOST=da-db.docker
      - DBPORT=5432
      - DBBACKUP=false
      - REDIS=redis://da-redis.docker:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    hostname: da-db.docker
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: abc123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -p 5432 -U postgres -v ON_ERROR_STOP=1 -c \"SELECT 1 FROM pg_database WHERE datname='docassemble'\" &> /dev/null" ]
      interval: 5s
      timeout: 30s
      retries: 20
    volumes:
      - ./volumes/db-mnt:/var/lib/postgresql/data
      - ./volumes/db-entrypoint:/docker-entrypoint-initdb.d
  redis:
    hostname: da-redis.docker
    image: redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - ./volumes/redis:/data
