services:
  docassemblesetup:
    image: ubuntu:22.04
    entrypoint:
      [
        "bash",
        "-c",
        "rm -r /usr/share/docassemble/backup/files/000/"
      ]
    volumes:
      - docassemblebackup:/usr/share/docassemble/backup
  docassemble:
    hostname: docassemble.docker
    #image: jhpyle/docassemble:latest
    image: daniel/docassemble:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - docassemblebackup:/usr/share/docassemble/backup
      - /mnt:/mnt/ro:ro
      - pip-conf:/var/www/.pip
      - /mnt/fakeMnt:/mnt/fakeMnt
      - ../docker-docassemble/volumes/live-config/config.yml:/usr/share/docassemble/config/config.yml
    stop_grace_period: 1m
    privileged: true
    cap_add:
      - SYS_ADMIN
    ports:
      - 5000:5000
      - 80:80
      - 443:443
      # - 5432:5432  # PostgreSQL
      - 6379:6379 # Redis
      - 5672:5672 # RabbitMQ
    environment:
      - CONTAINERROLE=web:celery:cron:redis:rabbitmq:log:mail # :sql
      - TIMEZONE=America/Phoenix
      # - DAUPDATEONSTART=false
      - DBHOST=doc-db.docker # docker container name
      - DBPORT=5432
      - DBBACKUP=false
    #depends_on:
    #  - db
  db:
    hostname: doc-db.docker
    #network_mode: bridge
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: abc123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready"]
    #  interval: 1s
    #  timeout: 5s
    #  retries: 10
    volumes:
      - ../docker-docassemble/volumes/db-mnt:/var/lib/postgresql/data
      - ../docker-docassemble/volumes/db-entrypoint:/docker-entrypoint-initdb.d
volumes:
  pip-conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../docker-docassemble/volumes/pip_conf'
  docassemblebackup:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../docker-docassemble/volumes/docassemble'
